engines:
  duplication:
    enabled: true
      config:
        languages:
          - php
  fixme:
    enabled: false
  phpmd:
    enabled: true

ratings:
  paths:
    - "**.php"

exclude_paths:
  - tests/
